locales:
  '/':
    lang: 'fr-FR'
    title: 'Introduction à Symfony'
    description: 'Licence Professionnelle SIL - Web et Mobile pour le Commerce Électronique'
head: [
  ["meta", { name: "robots", content: "noindex, nofollow" }]
]
markdown:
  lineNumbers: true
themeConfig:
  sidebarDepth: 2
  displayAllHeaders: true
  smoothScroll: false
  nav: [
    { text: 'Cours', link: '/cours/' },
    { text: 'Projets', link: '/projets/' },
    { text: 'Ressources', link: '/ressources/' },
  ]
  sidebar: {
    /cours/: [
      '/cours/',
      '/cours/installation',
      '/cours/structure',
      '/cours/bundle-et-flex',
      '/cours/controleur-et-routing',
      '/cours/twig',
      '/cours/formulaire',
      '/cours/injection-dependances',
      '/cours/service',
      '/cours/entities',
      '/cours/relations',
      '/cours/repositories',
      '/cours/security',
      '/cours/event-dispatcher',
      '/cours/mise-en-ligne',
      '/cours/plus-loin',
    ],
    /projets/: [
      '/projets/',
      '/projets/shoefony',
      '/projets/procost',
    ],
    /ressources/: [
      '/ressources/',
      '/ressources/glossaire',
      '/ressources/commandes',
      '/ressources/bundles',
      '/ressources/sources',
      '/ressources/git',
      # '/ressources/apprendre'
    ]
  }
