lang: 'fr-FR'
title: 'Symfony - LP WMCE Metz'
description: 'Ou comment devenir un ninja du web'
head: [
  ['link', { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css?family=Montserrat' }]
]
markdown:
  lineNumbers: true
themeConfig:
  displayAllHeaders: true
  nav: [
    { text: 'Home', link: '/' },
    { text: 'Cours', link: '/cours/' },
    # { text: 'Projets', link: '/projets/' },
    { text: 'Conventions', link: '/conventions/' },
  ]
  sidebar: {
    /cours/: [
      '/cours/',
      '/cours/installation',
      '/cours/structure',
      # '/cours/bundle',
    ],
    /projets/: [
      '/projets/',
      '/projets/shoefony',
    ]
  }
  
  