locales:
  '/':
    lang: 'fr-FR'
    title: 'Symfony - LP WMCE Metz'
    description: 'Ou comment devenir un ninja du web'
markdown:
  lineNumbers: true
themeConfig:
  sidebarDepth: 2
  displayAllHeaders: true
  nav: [
    { text: 'Cours', link: '/cours/' },
    { text: 'Projets', link: '/projets/' },
    { text: 'Ressources', link: '/ressources/conventions' },
  ]
  sidebar: {
    /cours/: [
      '/cours/',
      '/cours/installation',
      '/cours/structure',
      '/cours/bundle',
      '/cours/controleur-et-routing',
      '/cours/twig',
    ],
    /projets/: [
      '/projets/',
      '/projets/shoefony',
    ],
    /ressources/: [
      '/ressources/conventions',
      '/ressources/commandes',
      '/ressources/bundles'
    ]
  }
  
  