name: deploy
on:
    push:
        branches:
            - master
jobs:
    deploy:
        runs-on: ubuntu-20.04
        environment:
            name: github-pages
            url: ${{ steps.build_deploy.outputs.url }}
        steps:
            -   name: checkout
                uses: actions/checkout@master

            -   name: build_deploy
                uses: rreichel3/vuepress-github-actions-deploy@master
                env:
                    ACCESS_TOKEN: "$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}"
                    BUILD_DIR: docs/.vuepress/dist
                    BUILD_SCRIPT: npm install && npm run docs:build
                    PAGES_CNAME: ${{ secrets.PAGES_CNAME }}
                outputs:
                    url: "https://${{ secrets.PAGES_CNAME }}"
